yarnPath: "/Users/heymdall/Developer/work/ef/arui-scripts/.yarn/releases/yarn-berry.js"
pnpMode: "loose"
packageExtensions:
  "jest-runner@*":
    peerDependencies:
      "jest-environment-jsdom": "23.4.0"
